# List of tickers to analyze
tickers:
  - AAPL
  - NVDA
  - MSFT
  - GOOGL
  - TSLA
  - AXP
  - PANW

# Global portfolio settings
portfolio:
  cash: 10000.0

# Ticker-specific settings
positions:
  AAPL:
    stock: 0.23
  NVDA:
    stock: 0.44
  MSFT:
    stock: 0.12
  GOOGL:
    stock: 0.30
  TSLA:
    stock: 0.23
  AXP:
    stock: 0.20
  PANW:
    stock: 0.80